import type { Address,Hex } from 'viem'
export interface Token {address:Address;symbol:string;decimals:number}
export interface Pair {id:string;revision:number;chainId:number;pool:Address;feeTier:number;token0:Token;token1:Token;active:boolean}
export interface Program {id:string;revision:number;pairId:string;budgetPoolId:string;apr:number;days:number;minimumCents:string;maximumCents:string;sortOrder:number;isNew:boolean;active:boolean}
export interface Budget {campaign?:any;accounting?:any;id:string;revision:number;name:string;chainId:number;rewardAsset:Address;decimals:number;limitRaw:string;reservedRaw:string;allocatedRaw:string;availableRaw:string;paused:boolean;reconciliationRequired:boolean}
export interface Offer extends Pair,Program {pairRevision:number;capacityUsd:number;budget:Budget;eligibleMaximumCents:string|null;reviewMaximumCents?:string;availability:string|null}
export interface PriceSnapshot {quotePerToken:number;quoteUsd:number;observedAt:string;block:string}
export interface DeploymentProgress {version:1;reason:string;stages:{id:number;name:string;state:'pending'|'active'|'complete'|'blocked'|'checking';hash:Hex|null;confirmedAt:string|null}[];activeStage:number|null;requestedAt:string;acceptedAt:string;lastProgressAt:string;checkedAt:string;observedBlock:{number:string;hash:Hex;checkedAt:string}|null;verificationAvailable:boolean;operatorAction:boolean;paymentState:string;serviceWindowMinutes:number|null}
export interface Deployment {id:string;wallet:Address;positionWallet:Address;isRequester:boolean;programId:string;createdAt:string;planHash:Hex;plan:any;snapshot:any;signer:Address;observation:any;state:string;depositable:boolean;canClaim:boolean;canWithdraw:boolean;canRecover:boolean;workerState:string;fundingState:string;cancelRequested:boolean;error:string|null;transactions:{hash:Hex;originalHash:Hex;step:string;nonce:string;confirmed:boolean;reverted:boolean}[];nextAttemptAt:string;fundingOperator:Address|null;progress?:DeploymentProgress}
export const tokenAmount=(value:number)=>Number.isFinite(value)?value.toLocaleString('en-US',{maximumSignificantDigits:6}):'—'
export const usd=(value:number)=>value.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2})
export const compactUsd=(value:number)=>value.toLocaleString('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1})
export const statusLabel=(state:string)=>({queued:'Deployment queued',deploying:'Creating vault',checking:'Checking availability',retired:'Retired',needs_attention:'Needs operator attention',awaiting_funding:'Awaiting campaign funding',depositable:'Depositable',claimable:'Premium claimable',active:'Position active',matured:'Ready to withdraw',completed:'Completed',fixed_awaiting_funding:'Deposit confirmed · vault has not started',retirement_requested:'Retirement requested',occupied:'Fixed side occupied',no_position:'No position held'}[state]??state.replaceAll('_',' '))
