export const CHAIN_ID:4663
export const FACTORY:import('viem').Address
export function deploymentTypedData(quote:any):any
export function walletSessionMessage(proof:any):string
export function digest(value:any):import('viem').Hex
export function cents(value:string):string
export function normalizePair(value:any):any
export function normalizeProgram(value:any):any
export function normalizeBudget(value:any):any
export function validAddress(value:unknown):boolean
