import { test, expect } from '@playwright/test'
import { encodeFunctionData } from 'viem'
import { setup } from './fixture.mjs'
import { abi } from '../../shared/vault-lifecycle.mjs'
import { CASHCAT } from '../evm-fixture.mjs'

/** These replace the retired redirect tests with native lifecycle acceptance. */
test('paid request → operator creates → one-unit-short stays locked → funds → native modal → real fixed deposit', async ({page})=>{
  test.setTimeout(120000)
  const f=await setup(page,{native:true})
  try {
    await page.setViewportSize({width:1440,height:1000})
    await page.goto('/')
    await page.getByRole('button',{name:'Connect wallet',exact:true}).first().click()
    await page.getByRole('button',{name:'Uniswap Extension',exact:true}).click()
    await page.getByRole('button',{name:'Request CASHCAT / ETH, 3 days',exact:true}).click()
    await page.getByLabel('Deposit value in US dollars').fill('10')
    await page.getByRole('button',{name:'Continue',exact:true}).click()
    await page.getByRole('button',{name:'Request',exact:true}).click()
    await expect(page.getByText(/is paid and pending review/)).toBeVisible()
    await page.getByRole('button',{name:'Done',exact:true}).click()
    await page.getByRole('button',{name:/^My requests/}).click()
    await expect(page).toHaveURL(/\/portfolio\/requests$/)
    await expect(page.getByRole('button',{name:'Deposit',exact:true})).toHaveCount(0)
    const [row]=await f.database.list({wallet:f.account.address})
    await page.getByRole('button',{name:'Admin queue',exact:true}).click()
    await page.getByRole('button',{name:'Sign in as operator',exact:true}).click()
    await page.getByRole('button',{name:'Create vault',exact:true}).click()
    await expect.poll(async()=>(await f.database.lifecycle.job(row.requestId))?.state).toBe('queued')
    expect((await f.creator.tick()).state).toBe('created')
    await page.evaluate(()=>window.dispatchEvent(new Event('focus')))
    await expect(page.getByRole('link',{name:'View vault ↗',exact:true})).toBeVisible()
    await page.screenshot({path:'validation/native-admin-created.png',fullPage:true})
    let job=await f.database.lifecycle.job(row.requestId)
    const capacity=BigInt(job.plan.premium)
    await f.native.send(CASHCAT,encodeFunctionData({abi,functionName:'approve',args:[job.plan.vault,capacity]}))
    await f.native.send(job.plan.vault,encodeFunctionData({abi,functionName:'deposit',args:[capacity-1n,1n,'0x']}))
    await f.lifecycle.refresh(row.requestId)
    await page.goto('/portfolio/requests')
    await expect(page.getByText('Awaiting admin funding',{exact:true}).first()).toBeVisible()
    await expect(page.getByRole('button',{name:'Deposit',exact:true})).toHaveCount(0)
    await expect(page.getByText('Open variable side',{exact:true})).toHaveCount(0)
    await page.getByRole('button',{name:'Admin queue',exact:true}).click()
    await page.getByText('Admin premium funding',{exact:true}).click()
    await page.getByRole('button',{name:'Approve premium funding',exact:true}).click()
    await expect.poll(async()=>(await f.database.lifecycle.job(row.requestId))?.funding_state).toBe('queued')
    expect((await f.creator.tick()).state).toBe('funded')
    await page.goto('/portfolio/requests')
    await expect(page.getByText('Depositable',{exact:true})).toBeVisible()
    await page.setViewportSize({width:390,height:844})
    await page.screenshot({path:'validation/native-profile-funded-mobile.png',fullPage:true})
    await page.getByRole('button',{name:'Deposit',exact:true}).click()
    await expect(page.getByLabel('Vault deposit summary')).toBeVisible()
    await expect(page.getByRole('button',{name:'Approve CASHCAT',exact:true})).toBeEnabled()
    await page.screenshot({path:'validation/native-deposit-mobile.png',fullPage:true})
    f.state.loseNativeResponse = true
    await page.getByRole('button',{name:'Approve CASHCAT',exact:true}).click()
    await expect(page.getByLabel('Recover transaction hash')).toBeVisible()
    await page.reload()
    await page.getByRole('button',{name:'Resume transaction',exact:true}).click()
    await page.getByLabel('Recover transaction hash').fill(f.state.lastNativeHash)
    await page.getByRole('button',{name:'Check transaction',exact:true}).click()
    await expect(page.getByRole('button',{name:'Approve ETH',exact:true})).toBeEnabled()
    await page.getByRole('button',{name:'Approve ETH',exact:true}).click()
    await expect(page.getByRole('dialog').getByRole('button',{name:'Deposit',exact:true})).toBeEnabled()
    await page.getByRole('dialog').getByRole('button',{name:'Deposit',exact:true}).click()
    await expect(page.getByText(/Fixed deposit confirmed/)).toBeVisible()
    expect(f.state.sends).toBe(1)
    expect(f.state.nativeSends).toBe(3)
    expect(await f.native.client.readContract({address:job.plan.vault,abi,functionName:'isStarted'})).toBe(true)
    await expect(page.locator('a[href*="/network/robinhood"]')).toHaveCount(0)
    expect(new URL(page.url()).pathname).toBe('/portfolio/requests')
  }finally{await f.close()}
})
