// The concept is a closed, in-memory prototype: no network, storage or wallet APIs.
const $=selector=>document.querySelector(selector);
const icons={Home:'M3 10l9-7 9 7v11h-6v-7H9v7H3z',Portfolio:'M4 5h16v15H4z M8 5V3h8v2 M8 11h8 M8 16h8','Live APR':'M3 19l6-7 4 3 7-11 M14 4h6v6',More:'M5 6h14 M5 12h14 M5 18h14'};
const svg=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]}"></path></svg>`;
const pairIcons=()=>`<span class="pair-icons"><img src="${assets.cashcat}" alt="CASHCAT"><img src="${assets.eth}" alt="ETH"></span>`;
const money=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD'});
let state={view:'Home',sheet:null,days:3,amount:'100',connected:false,scenario:'normal',admin:false,compares:[],keyboard:false,created:0};
let opener=null,noticeTimer;
const premium=()=>Number(state.amount)*(state.days===3?.01:state.days===5?.03510548:.04914768);
const primary=(label,action,disabled=false)=>`<button class="primary-button" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const blank=()=>`<div class="empty"><div class="empty-mark">◇</div><h2>Your first vault starts here.</h2><p>Choose an incentive. Every paid request creates a separate vault.</p>${primary('Explore incentives','home')}</div>`;
const position=(active=true,index=1)=>`<article class="position"><div class="row"><span class="pill ${active?'green':'gold'}">${active?'Position active':'Awaiting funding'}</span><small>3 days</small></div><h3>CASHCAT / ETH</h3><dl><div><dt>LP value at request</dt><dd>${active?'$1,000.00':'$100.00'}</dd></div><div><dt>Committed incentive</dt><dd class="success">${active?'$10.00':'$1.00'}</dd></div></dl><p class="request-id">Sample request ${String(index).padStart(3,'0')}</p><div style="margin-top:14px">${primary(state.scenario==='offline'?'View request':active?'View position':'View progress',active?'position':'progress')}</div></article>`;
/** Render only presentation state; navigation preserves the unpaid draft. */
function render(){
 $('.connect').textContent=state.connected?'0x71…9a2F':'CONNECT';
 $('.bottomnav').innerHTML=Object.keys(icons).map(name=>`<button data-nav="${name}" class="${state.view===name?'selected ':''}${name==='Live APR'?'apr':''}" ${state.view===name?'aria-current="page"':''}>${svg(name)}<span>${name}</span></button>`).join('');
 let html='';
 if(state.view==='Home')html=`<header><div class="row"><h1>Liquidity incentives</h1></div><p class="intro">Create a vault. Deposit LP assets when it is ready. Claim your incentive after it starts.</p><details class="how"><summary>How it works</summary><p>Pay the $2 request fee in ETH. We fund the premium after creation. Your LP is locked for the chosen duration after start.</p></details></header><div class="row"><div class="pair-title">${pairIcons()} CASHCAT / ETH</div><span class="chain"><img src="${assets.robinhood}" alt="">Robinhood</span></div>${[[3,'121.67%','$500,000'],[5,'256.27%','$700,000'],[7,'256.27%','$900,000']].map(([days,apr,tvl],index)=>`<button class="campaign" data-days="${days}" aria-label="Create CASHCAT / ETH, ${days} days"><span class="primary"><span class="apr">${apr} <span class="label">APR</span></span>${!index?'<span class="new">NEW</span>':'<span class="arrow">↗</span>'}</span><span class="metrics"><span class="metric"><span class="label">Duration</span><strong>${days} days</strong></span><span class="metric"><span class="label">TVL</span><strong>${tvl}</strong></span></span></button>`).join('')}<p class="footnote">Illustrative TVL · each paid request creates a separate vault.</p>`;
 if(state.view==='Portfolio')html=`<header><h1>Portfolio</h1><p class="intro">Your requests and positions, in one place.</p></header>${state.admin?'<div class="banner" style="margin-bottom:14px">Admin only · premium budget near its planning target. Requests remain open.</div>':''}${state.scenario==='offline'?'<div class="banner error" style="margin-bottom:14px">Verification is unavailable. Last known positions are shown; new actions are paused.</div>':''}${state.scenario==='lost'?'<article class="position lost" style="margin-bottom:14px"><h3>Creation payment saved</h3><p class="intro">The response was interrupted. Check this payment without paying again.</p><button style="width:100%;margin-top:14px" data-action="recover">Check saved payment</button></article>':''}${state.scenario==='empty'?blank():`${state.created?position(false,3):''}${position(true,1)}${position(false,2)}<button class="refresh" data-action="refresh">Refresh vaults</button><p class="footnote">Refresh checks the same saved requests. It does not start another test or create another vault.</p>`}`;
 if(state.view==='Live APR')html=`<header><div class="row"><h1>Live APR</h1><span class="pill green">Illustration</span></div><p class="intro">Pool fees measured over your observation window. No wallet required.</p></header><button class="pool-select" data-action="pools">NVDA / USDG <small>0.05% ▾</small></button><article class="apr-card"><div class="row"><span class="label">Measured pool APR</span><span class="pill">12m window</span></div><p class="big">84.12%</p><small>Sample observation · not a campaign return</small><div class="metrics"><div><span class="label">Pool TVL</span><b>$1.24M</b></div><div><span class="label">Observed fees</span><b>$23.82</b></div></div><div class="mini-history"><span>4m<strong>72.40%</strong></span><span>8m<strong>81.03%</strong></span><span>12m<strong>84.12%</strong></span></div></article>${state.compares.map((name,i)=>`<div class="compare"><span>${name}<br><small>Independent observation</small></span><span class="gold">${[36.42,48.17,21.85][i]}%</span><button data-remove="${i}" aria-label="Remove ${name}">×</button></div>`).join('')}<button class="refresh" data-action="compare" ${state.compares.length===3?'disabled':''}>${state.compares.length===3?'Three comparisons added':'+ Compare a pool'}</button><div class="row" style="margin-top:12px"><button data-action="export">Copy card as PNG</button><button data-action="history">History</button></div><p class="footnote">All values in this document are illustrative. The implementation retains the existing live data source and verified PNG export.</p>`;
 if(state.view==='More')html=`<header><h1>More</h1><p class="intro">Secondary destinations stay one tap away.</p></header><div class="menu-list"><button data-action="wallet">Wallet & network <span>→</span></button><a class="external" href="https://app.saffron.finance/" target="_blank" rel="noreferrer">Saffron pro <span>↗</span></a><button data-action="stats">Stats <span>→</span></button><button data-action="community">Community <span>→</span></button><button data-action="audits">Audits & resources <span>→</span></button>${state.admin?'<button data-action="admin">Campaign administration <span>→</span></button>':''}<button data-action="about">About this concept <span>→</span></button></div>`;
 $('#app').innerHTML=html;
}
function toast(message){clearTimeout(noticeTimer);$('.notice').textContent=message;$('.notice').hidden=false;noticeTimer=setTimeout(()=>$('.notice').hidden=true,3500)}
/** A real native dialog supplies focus containment and Escape dismissal. */
function openSheet(kind){
 state.sheet=kind;const dialog=$('dialog');if(!dialog.open){opener=document.activeElement;dialog.showModal()}
 const body=$('.sheetbody'),foot=$('.sheetfoot');let title='',content='',actions='';
 $('.sheethead [data-action=back]').style.visibility=['review','assets'].includes(kind)?'visible':'hidden';
 if(kind==='amount'){
  title='Create an incentive vault';content=`<div class="stack"><div class="row"><span class="pair-title">${pairIcons()} CASHCAT / ETH</span><span class="pill">${state.days} days</span></div><div><label class="deposit-label" for="amount">Deposit value in US dollars</label><input class="deposit-input" id="amount" inputmode="decimal" autocomplete="off" value="${state.amount}" aria-describedby="amount-error"><p id="amount-error" role="alert"></p></div><div class="summary-card"><div class="row"><span>You get</span><strong class="reward" data-reward>${money(premium())}</strong></div><small>Committed incentive value at request</small></div><details><summary>LP details · full range</summary><div class="asset-list"><div><span><img src="${assets.cashcat}" alt="">CASHCAT</span><span>25,000</span></div><div><span><img src="${assets.eth}" alt="">ETH</span><span>0.0249</span></div></div><p class="small" style="margin-top:10px">Illustrative token amounts. Refresh actual LP amounts before the later deposit confirmation.</p></details></div>`;actions=primary('Continue','continue')+'<p>No wallet transaction at this step.</p>';
 }
 if(kind==='review'){
  title=`Claim ${money(premium())}`;content=`<div class="stack"><span class="quiet-title">${pairIcons()} CASHCAT / ETH · ${state.days} days</span><ul class="review-list"><li>You deposit <button class="details-button" data-action="assets">${money(state.amount)}</button> into Uniswap v3.</li><li>You get a committed token premium worth <b class="success">${money(premium())}</b> at request. Claim it after the vault starts.</li><li>Lock time: <b>${state.days} days after start</b>.</li></ul><details><summary>Details</summary><p>The operator funds the premium before LP entry. LP amounts are refreshed before you explicitly confirm a deposit. Full range does not remove price risk.</p></details></div>`;actions='<p class="fee" style="margin:0 0 12px;text-align:left">Creation fee: $2 in ETH plus gas.</p>'+primary(`Claim ${money(premium())}`,'pay')+'<p>Prototype action only · no payment is sent.</p>';
 }
 if(kind==='progress'){
  title='Your incentive vault';const offline=state.scenario==='offline';content=`<div class="stack"><div><h3>${offline?'Verification temporarily unavailable':'Awaiting campaign funding'}</h3><p class="small" style="margin-top:7px">Elapsed 2m 18s · illustrative progress</p></div><p class="intro" style="margin:0">You can close this window. Return through Portfolio to the same request.</p><ol class="steps">${['Prepare adapter','Create vault','Initialize and verify','Fund premium and enable entry'].map((name,i)=>`<li><span class="step-dot ${i<3?'done':offline?'':'active'}">${i<3?'✓':4}</span><div>${name}<small>${i<3?'Complete':offline?'Verification paused':'In progress'}</small></div></li>`).join('')}</ol>${offline?'<div class="banner error">Last known progress is preserved. Deposit stays unavailable until verification returns.</div>':'<p class="small">The operator must fund the entire premium before LP entry becomes available.</p>'}<details><summary>Deployment details</summary><p>No transaction hashes are invented in this mockup. The implementation links only verified receipts.</p></details></div>`;actions=primary('Check progress','refresh')+'<p>Checks the existing request. Does not restart it.</p>';
 }
 if(kind==='recover'){
  title='Recover your payment';content=`<div class="stack"><div class="banner">Your saved payment may already be confirmed. Do not pay the fee again.</div><p class="intro" style="margin:0">Reconnect the same wallet, then check the original payment.</p><label class="deposit-label">Payment transaction hash<input class="inline-input" placeholder="Use the saved hash, or paste it here" aria-label="Payment transaction hash"></label><details><summary>What happened?</summary><p>The browser or wallet response was interrupted. The API and payment watcher can still find the canonical payment.</p></details></div>`;actions=primary('Check payment','recovered')+'<p>No second payment. No separate progress tracker.</p>';
 }
 if(kind==='position'){
  title='CASHCAT / ETH';content=`<div class="stack"><span class="pill green">Position active</span><div class="summary-card"><div class="row"><span>LP value at request</span><b>$1,000.00</b></div><div class="row"><span>Premium claimed</span><b class="success">$10.00</b></div></div><div class="date-grid"><div><small>Vault started</small><strong>12 Sep · 10:30 UTC</strong></div><div><small>Maturity</small><strong>15 Sep · 10:30 UTC</strong></div></div><p class="intro">Your LP stays locked until maturity. Current bearer ownership determines who can act.</p><details><summary>Position details</summary><p>Sample position · three-day lock. The real UI uses verified chain timestamps and current balances.</p></details></div>`;actions=primary('Locked until maturity','locked',true)+'<p>Withdrawal becomes available only after verification.</p>';
 }
 if(kind==='deposit'){
  const steps=['Wrap ETH','Approve CASHCAT','Approve ETH','Deposit LP assets'];const index=state.entryStep||0;
  title='Confirm your LP deposit';content=`<div class="stack"><span class="pill green">Vault ready · premium funded</span><p class="intro">Review refreshed LP quantities before approving this deposit.</p><div class="summary-card"><div class="row"><span>CASHCAT</span><b>25,000</b></div><div class="row"><span>ETH</span><b>0.0249</b></div><div class="row"><span>LP value estimate</span><b>$100.00</b></div></div><p class="small">Illustrative amounts · full range · refreshed just now in this scenario. The real confirmation must use fresh data.</p><ol class="steps">${steps.map((step,i)=>`<li><span class="step-dot ${i<index?'done':i===index?'active':''}">${i<index?'✓':i+1}</span><span>${step}<small>${i<index?'Confirmed':i===index?'Ready for wallet confirmation':'Next'}</small></span></li>`).join('')}</ol></div>`;actions=primary(steps[index],'advance-deposit')+'<p>Each real step requires explicit wallet confirmation.</p>';
 }
 if(kind==='claim'){
  title='Your premium is ready';content='<div class="stack"><span class="pill green">Vault started</span><h3 class="reward">499.99 CASHCAT</h3><p class="intro">Committed premium worth $1.00 at request. Claiming does not unlock your LP early.</p><div class="date-grid"><div><small>Started</small><strong>12 Sep · 10:30 UTC</strong></div><div><small>Maturity</small><strong>15 Sep · 10:30 UTC</strong></div></div></div>';actions=primary('Claim premium','claim-demo')+'<p>Prototype action only · no transaction.</p>';
 }
 if(kind==='matured'){
  title='Your LP is ready to withdraw';content='<div class="stack"><span class="pill green">Matured · ownership verified</span><div class="summary-card"><div class="row"><span>CASHCAT</span><b>24,820</b></div><div class="row"><span>ETH</span><b>0.0251</b></div></div><p class="intro">Illustrative final quantities. Real amounts can differ from entry because of price movement and fees.</p><p class="small">Matured 15 Sep · 10:30 UTC. Recheck the current position and wallet before submitting.</p></div>';actions=primary('Withdraw LP assets','withdraw-demo')+'<p>Explicit wallet confirmation is required.</p>';
 }
 if(kind==='completed'){title='Position completed';content='<div class="stack"><span class="pill green">LP withdrawn</span><p class="intro">Your sample position is complete. Keep the record in Portfolio.</p></div>';actions=primary('Back to Portfolio','portfolio')}
 if(kind==='wallet'){
  title='Connect your wallet';content='<div class="stack"><p class="intro">Choose a wallet. Return to this same review after the wallet opens.</p><div class="menu-list"><button data-action="connect">MetaMask <span>→</span></button><button data-action="connect">Uniswap Wallet <span>→</span></button></div><p class="small">Prototype connection only. The actual provider handles account selection and confirmation.</p></div>';actions='<button class="neutral" data-action="close">Cancel</button>';
 }
 if(kind==='assets'){title='Your LP tokens';content=`<div class="stack"><div class="asset-list"><div><span><img src="${assets.cashcat}" alt="">CASHCAT</span><b>25,000</b></div><div><span><img src="${assets.eth}" alt="">ETH</span><b>0.0249</b></div></div><p class="intro">Deposited to Uniswap v3. Values are illustrative; the implementation refreshes actual amounts before LP entry.</p></div>`;actions=primary('Back to review','review')}
 if(kind==='pools'){title='Choose a pool';content='<div class="menu-list">'+['NVDA / USDG · 0.05%','CASHCAT / ETH · 1%','ZZZ / ETH · 1%'].map(n=>`<button data-pool="${n}">${n}<span>→</span></button>`).join('')+'</div>';actions='<p>Pool selection starts a fresh observation in the real app.</p>'}
 if(!content){title={history:'Observation history',admin:'Campaign administration',about:'Saffron mobile concept',stats:'Stats',community:'Community',audits:'Audits & resources',export:'Card export'}[kind]||'Details';content=`<div class="stack"><p class="intro">${kind==='history'?'Each observation keeps its own baseline and history. Pool changes must not reuse a stale APR.':kind==='export'?'The production feature already copies the selected pool card as PNG. This design reserves a touch-friendly action for it; the mockup does not generate a fake success.':kind==='admin'?'Keep campaign configuration behind the operator session. Budget planning remains advisory and appears only in the admin Portfolio.':kind==='about'?'This is a self-contained HTML design prototype. All data and interactions are illustrative. It sends no requests, writes no browser storage and cannot move funds.':'Preserve this existing destination under More. Do not invent live statistics or announcements.'}</p></div>`;actions='<button class="neutral" data-action="close">Close</button>'}
 $('#sheet-title').textContent=title;if(kind==='review')$('#sheet-title').innerHTML='Claim <span class="success">'+money(premium())+'</span>';body.innerHTML=content;foot.innerHTML=actions;body.scrollTop=0;
 requestAnimationFrame(()=>{const target=kind==='amount'?$('#amount'):$('.sheethead [data-action=close]');target?.focus({preventScroll:true})});
}
function closeSheet(){state.sheet=null;$('dialog').close();if(opener?.isConnected)opener.focus({preventScroll:true})}
function navigate(view){if($('dialog').open)closeSheet();state.view=view;render();$('#app').scrollTop=0}
document.addEventListener('input',event=>{if(event.target.id!=='amount')return;state.amount=event.target.value.replace(/[^\d.]/g,'');const valid=Number.isFinite(Number(state.amount))&&Number(state.amount)>0;$('.sheetfoot button').disabled=!valid;$('[data-reward]').textContent=valid?money(premium()):'—';$('#amount-error').textContent=valid?'':'Enter a positive deposit value.'});
document.addEventListener('click',event=>{
 const target=event.target.closest('button');if(!target||target.disabled)return;
 if(target.dataset.nav){navigate(target.dataset.nav);return}
 if(target.dataset.days){state.days=Number(target.dataset.days);openSheet('amount');return}
 if(target.dataset.pool){closeSheet();toast('Prototype pool selection: '+target.dataset.pool);return}
 if(target.dataset.remove){state.compares.splice(Number(target.dataset.remove),1);render();return}
 const action=target.dataset.action;
 if(action==='close'){closeSheet();return}
 if(action==='back'){openSheet(state.sheet==='assets'?'review':'amount');return}
 if(action==='continue'){if(Number(state.amount)>0)openSheet('review');return}
 if(action==='pay'){state.created++;state.scenario='normal';state.view='Portfolio';render();openSheet('progress');return}
 if(action==='recovered'){state.scenario='normal';render();openSheet('progress');return}
 if(action==='connect'){state.connected=true;closeSheet();render();toast('Demo wallet connected. No wallet provider was contacted.');return}
 if(action==='advance-deposit'){state.entryStep=(state.entryStep||0)+1;openSheet(state.entryStep===4?'claim':'deposit');return}
 if(action==='claim-demo'){openSheet('position');return}
 if(action==='withdraw-demo'){openSheet('completed');return}
 if(action==='portfolio'){navigate('Portfolio');return}
 if(action==='home'){navigate('Home');return}
 if(action==='refresh'){toast(state.scenario==='offline'?'Still offline in this scenario. Last known state is retained.':'The same sample request was checked. No new request was created.');return}
 if(action==='compare'){if(state.compares.length<3){state.compares.push(['CASHCAT / ETH','ZZZ / ETH','PONS / USDG'][state.compares.length]);render()}return}
 if(action)openSheet(action);
});
$('dialog').addEventListener('cancel',event=>{event.preventDefault();closeSheet()});
/** Only fixed design commands are accepted; no URLs, HTML or executable input. */
window.addEventListener('message',event=>{
 if(event.source!==parent||event.data?.type!=='saffron-design')return;
 const {command,value}=event.data;
 if(command==='view'&&['Home','Portfolio','Live APR','More'].includes(value))navigate(value);
 if(command==='scenario'&&['normal','empty','lost','offline','admin'].includes(value)){state.admin=value==='admin';state.scenario=value==='admin'?'normal':value;navigate('Portfolio')}
 if(command==='keyboard'){state.keyboard=Boolean(value);document.body.classList.toggle('keyboard-on',state.keyboard);if(state.keyboard&&!$('dialog').open)openSheet('amount')}
 if(command==='scene'&&['amount','review','progress','recover','position','deposit','claim','matured','wallet'].includes(value)){state.entryStep=0;openSheet(value)}
 if(command==='reset'){state={view:'Home',sheet:null,days:3,amount:'100',connected:false,scenario:'normal',admin:false,compares:[],keyboard:false,created:0};document.body.classList.remove('keyboard-on');if($('dialog').open)closeSheet();render()}
});
render();
if(['amount','review','progress','recover','position','deposit','claim','matured','wallet'].includes(initialView))openSheet(initialView);
else if(initialView==='offline'){state.scenario='offline';navigate('Portfolio')}
else if(initialView!=='Home')navigate(initialView);
