#!/usr/bin/env python3
"""Build the full offline HTML design study from editable document/app sources.

The approved app supplies licensed fonts and local token/emblem images. The
Clawbee renderer supplies native disclosures, contents navigation and print-state
restoration. This historical generator requires an explicitly installed external
renderer. The frozen HTML is the maintained reference artifact.
"""
import base64
import html
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parent
APP = ROOT.parent / 'live-apr-merge'
if len(sys.argv) != 2:
    raise SystemExit('Historical generator: supply an installed renderer directory. The frozen HTML needs no renderer.')
RENDERER = Path(sys.argv[1]).resolve()
if not (RENDERER / 'scripts/render.py').is_file():
    raise SystemExit('The selected renderer must provide scripts/render.py')

def data(path, mime):
    return 'data:' + mime + ';base64,' + base64.b64encode(path.read_bytes()).decode()

FONT = '@font-face{font-family:Funnel;src:url("' + data(APP/'src/host/fonts/FunnelDisplay.woff2','font/woff2') + '") format("woff2");font-weight:300 700;font-display:swap}'
ASSETS = {name:data(APP/'public'/file,mime) for name,file,mime in [('cashcat','cashcat.png','image/png'),('eth','eth.svg','image/svg+xml'),('robinhood','robinhood.svg','image/svg+xml')]}
EMBLEM = data(APP/'public/emblem.png','image/png')

def phone(view='Home', key='', main=False):
    """Embed a complete HTML mockup, isolated from report CSS and document state."""
    source=(ROOT/'app.html').read_text().replace('__FONT__',FONT).replace('__CSS__',(ROOT/'app.css').read_text()).replace('__EMBLEM__',EMBLEM).replace('__ASSETS__',json.dumps(ASSETS)).replace('__INITIAL__',json.dumps(view)).replace('__JS__',(ROOT/'app.js').read_text())
    identity=' id="mobile-prototype"' if main else ''
    return '<div class="device-dock"><div class="device"'+(' id="main-device"' if main else '')+'><iframe'+identity+' title="'+html.escape(key or view,quote=True)+' mobile mockup" sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox" loading="'+('eager' if main else 'lazy')+'" srcdoc="'+html.escape(source,quote=True)+'"></iframe></div></div>'

def mock(view,number,title,description):
    return '<article class="mockup"><div class="step-number">'+number+'</div><h3>'+title+'</h3><p>'+description+'</p>'+phone(view,title)+'</article>'

def table(head,rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

sections=[]
def section(key,title,body):
    sections.append({'id':key,'title':title,'body_html':body})

section('experience','01 / The recommendation', '''
<div class="now-next"><div><div class="kicker scope-live">Changed in the current app</div><h3>15% brighter modal buttons</h3><p>Mouse hover now uses <code>brightness(1.15)</code> at full opacity. Disabled controls are unchanged. This is separate from the mobile proposal below.</p></div><div><div class="kicker scope-plan">Proposed — not deployed</div><h3>A mobile layout with its own priorities</h3><p>Keep the Saffron visual language. Change the layout, navigation and sheet behavior for a smaller screen. Keep desktop and all payment contracts intact.</p></div></div>
<div class="hero-links"><a href="#interactive">Try the mobile prototype ↓</a><a class="secondary" href="#flow">Explore the complete request flow</a><a class="secondary" href="#delivery">Read the implementation plan</a></div>
<div class="split" id="interactive"><div class="vision"><div class="kicker">Same product. Less reaching.</div><h3>Your next action stays within reach.</h3><p>Use one compact header, four bottom-navigation destinations and focused cards. Move explanations into optional disclosures. Give every important transaction step its own readable sheet.</p><ul class="feature-list"><li><span>01</span><div><b>Home earns the first screen</b><small>APR, duration and TVL fit in a compact offer card. The first offer no longer sits below a large block of navigation and copy.</small></div></li><li><span>02</span><div><b>Portfolio is always one tap away</b><small>Saved payments, C06 requests and owned positions share a stable destination. Refresh never starts over.</small></div></li><li><span>03</span><div><b>One action per sheet</b><small>The explanation scrolls; Back, Close and the primary action stay reachable. Wallet switching does not discard the draft.</small></div></li><li><span>04</span><div><b>APR remains a live-data feature</b><small>A touch-friendly pool picker and stacked comparisons preserve independent observations and the existing export action.</small></div></li></ul><div class="callout"><strong>Use the prototype.</strong> Open a campaign, enter an amount, continue to review and press Claim. Navigate between Home, Portfolio, Live APR and More. All actions are local illustrations; no wallet, API, storage or funds are used.</div></div><div><div class="prototype-tools"><div class="controls"><label>Frame width<select id="device-width"><option value="320">320 px</option><option value="390" selected>390 px</option><option value="430">430 px</option></select></label><label>Portfolio state<select id="prototype-state"><option value="normal">Normal</option><option value="empty">Empty</option><option value="lost">Saved payment</option><option value="offline">Verification unavailable</option><option value="admin">Admin advisory</option></select></label></div><div class="controls"><label>Open a flow screen<select id="prototype-scene"><option value="">Choose a screen</option><option value="amount">Deposit amount</option><option value="review">Request review</option><option value="wallet">Wallet handoff</option><option value="progress">C06 progress</option><option value="recover">Payment recovery</option><option value="deposit">LP deposit</option><option value="claim">Claim premium</option><option value="matured">Mature withdrawal</option></select></label></div><div class="controls"><label class="check"><input type="checkbox" id="keyboard-demo">Simulate keyboard space</label><button id="reset-prototype">Reset mockup</button></div></div>'''+phone('Home','Interactive Saffron',True)+'''<p class="device-caption">Interactive HTML · nominal 390 px frame · shrinks to fit this document<br>Keyboard control is a layout simulation, not an operating-system keyboard test.</p></div></div>
''')

section('flow','02 / The complete request journey','''<p class="lead">Keep the existing sequence. Make each step easy to understand and easy to return to.</p><p>These are HTML mockups, not screenshots. Buttons, disclosures, input fields and native dialogs work. Values are illustrative. A completed mock interaction is not evidence of a blockchain transaction.</p><div class="gallery">'''+
mock('amount','STEP 01','Choose the LP amount','Use a 16 px minimum input text size; show a large amount and a clear premium summary. Keep LP details available without making the default sheet long.')+
mock('review','STEP 02','Review the creation request','Keep the approved Claim $X label, green reward amount and Back action. Make the separate $2 ETH fee legible above the primary action.')+
mock('wallet','STEP 03','Hand off to the wallet','Keep wallet choice explicit. The app must preserve the request, selected account and intended chain when the wallet application takes focus.')+
mock('progress','STEP 04','Return to C06','Show four verified creation stages. Closing this sheet does not cancel or reset the request. Preserve completed stages through a verification outage.')+
mock('deposit','STEP 05','Confirm the actual LP deposit','Only after full premium funding: refresh quantities, then show the exact wrap/approval/deposit sequence. Each real transaction remains a separate explicit confirmation.')+
mock('claim','STEP 06','Claim the premium after start','Make claimable premium distinct from the original request action. The LP remains locked until its verified maturity time.')+
mock('position','STEP 07','Follow an active position','Show start and maturity together, with an explicit timezone. Keep withdrawal disabled before maturity; a countdown is not authorization.')+
mock('matured','STEP 08','Withdraw at maturity','Use current ownership and fresh quantities to enable the action. Preserve the completed record after withdrawal. No retirement or refund-request workflow returns.')+
'''</div><div class="callout gold"><strong>Transaction rules do not change.</strong> Canonical fee verification, exact quote validity, ownership checks, recovery, full premium funding and explicit wallet confirmations stay in the existing hooks/API. The mobile work changes presentation and navigation only.</div>''')

section('destinations','03 / Home, Portfolio and Live APR','''<p class="lead">Put the three frequent destinations in the bottom bar. Put the rest in More.</p>'''+table(['Destination','Mobile treatment','Preserve'],[
('Home','Single-line brand header. Concise introduction. Full-card offer hit area. APR first; Duration and TVL side by side.','Three preview offers and existing row order. TVL uses Duration typography. No public budget-capacity disclosure.'),
('Portfolio','Status-first request cards, then position value, premium and one contextual action. Separate saved-payment recovery card.','API/database source of truth; durable local recovery records; multiple independent paid requests.'),
('Live APR','Touch-friendly pool picker; one primary card; comparisons stack beneath it. History stays available in a disclosure/sheet.','Independent baselines, canonical routes, up to three comparisons, data-unavailable states and selected-card PNG export.'),
('More','Wallet/network, Saffron pro, Stats, Audits and Community. Campaigns/Administration only when the existing role permits them.','Every existing destination. No invented live statistics. External links remain clearly external.')])+
'''<div class="gallery">'''+mock('Portfolio','DESTINATION 02','Status first, detail second','Keep action labels contextual: View progress, Deposit, Claim premium, Withdraw or View request. Do not squeeze status and a long pair name into the same line.')+mock('Live APR','DESTINATION 03','Live APR is not campaign APR','Use existing price/fee data and observation semantics. This mockup uses a numeric history strip rather than introducing a new chart library.')+'''</div><details class="finding" id="navigation-contract"><summary><h3><span class="tag">Navigation contract</span>Keep one router and one route owner</h3></summary><p>Bottom-navigation destinations map to the existing Home, Portfolio and Live APR routes. More can be a local navigation sheet; it does not create a second router. Browser Back, direct links, query strings and pool aliases must continue to work.</p><p>Leave the desktop sidebar and its approved hover/selected treatment unchanged above the desktop breakpoint. Do not render both a horizontal mobile menu and a fixed bottom bar.</p></details>''')

section('responsive','04 / Responsive layout rules','''<p class="lead">Use the available pane width—not a guessed device name—to choose the layout.</p><div class="grid-3"><div class="spec-card"><strong>320–599 px</strong><p>Phone: one content column, four bottom destinations, full-width bottom sheets, two metrics per offer row.</p></div><div class="spec-card"><strong>600–1000 px</strong><p>Tablet/compact pane: keep touch navigation, use two-column cards where the pane permits them, and center sheets at a readable maximum width.</p></div><div class="spec-card"><strong>1001 px+</strong><p>Desktop: retain the current rail and table. Container width still decides whether a card or table fits when the rail changes.</p></div></div>'''+table(['Rule','Proposal','Acceptance gate'],[
('Main gutters','16 px on phones; 24 px in tablet panes. Avoid a permanent 64 px collapsed rail on narrow screens.','No body-level horizontal scroll at 320, 360, 390, 430, 600, 768 and 1000 px.'),
('Offer hierarchy','APR at 28–30 px. Duration and TVL at 20 px with identical font, weight and numeric settings. Labels at 11–12 px.','All three fields remain readable with $9,999,999 and a two-digit duration; allow layout changes, not text overlap.'),
('Touch targets','Minimum 44 × 44 CSS px; prefer 48 px for primary actions. Give adjacent controls at least 8 px breathing room.','Back, Close, pool selection, recovery and primary actions all meet the target.'),
('Navigation','Four labelled destinations; bottom safe-area padding. Content padding includes the navigation height.','The final item and focused control are never hidden under the bar.'),
('Sheets','Use 100dvh with fallbacks, a maximum readable width and independent header/body/footer areas. Scroll only the body when necessary.','Close and the CTA stay reachable on a 320 × 568 viewport and after content/error expansion.'),
('Keyboard','Input text at least 16 px. Keep the focused field visible; move the CTA above the visual keyboard. Use visualViewport only if CSS/browser behavior requires it.','Verify on real iOS Safari and Android Chrome with the native keyboard, including rotation and wallet return.'),
('Large text','Respect browser text zoom. Reflow labels and allow card height to grow; do not scale the whole page down.','Manual 200% text/zoom check preserves labels, navigation and every action.')])+
'''<p class="small">Breakpoints are proposed, not measured performance claims. The implementation should use the existing shell breakpoint as its starting seam, then qualify the resulting pane sizes. The document’s embedded frames approximate content width; browser chrome and OS insets still need device checks.</p>''')

section('visual','05 / The Saffron visual contract','''<p class="lead">Keep what makes this our page.</p><div class="swatches"><div class="swatch"><i style="--swatch:#000"></i>Canvas · #000000</div><div class="swatch"><i style="--swatch:#0a0a0a"></i>Cards · #0A0A0A</div><div class="swatch"><i style="--swatch:#ffbc09"></i>APR · #FFBC09</div><div class="swatch"><i style="--swatch:#d286ff"></i>Accent · #D286FF</div><div class="swatch"><i style="--swatch:#9a29b8"></i>Selected · #9A29B8</div></div>'''+table(['Element','Keep / adapt'],[
('Typeface','Embed/reuse Funnel Display. Keep the restrained white/gray hierarchy, warm gold APR and green claim amount. Font license remains included with the app source.'),
('Cards','Near-black surfaces, subtle gray borders, modest corner radii and generous alignment. No light dashboard theme or dense generic table on phones.'),
('Selected navigation','Use the existing purple Afterglow family. Selected Live APR text is white; its inactive state retains gold/purple APR paint.'),
('Buttons','Keep approved modal primary surfaces. Mouse hover brightens by 15% at full opacity, with a short transition. Touch uses a clear pressed/focus state, not a sticky hover dependency.'),
('Motion','Use small, nonessential transitions. Respect reduced motion. C06 state and verification never depend on an animation completing.'),
('Data','TVL placeholders are display-only. Do not repurpose private planning targets as public TVL or show unavailable data as zero.'),
('Density','Reduce repeated chrome and explanatory text, not the information needed to consent to a fee or deposit. Use disclosures for secondary detail.')])+
'''<div class="callout">The mockups deliberately reuse the app’s embedded font, emblem and token imagery. They do not rely on external fonts, CDNs, a screenshot service or a network connection.</div>''')

section('edges','06 / Recovery and difficult states','''<p class="lead">Design the interruptions with the same care as the successful path.</p><div class="gallery">'''+mock('recover','RECOVERY','A payment response is missing','A durable payment card remains in Portfolio. Check the original hash/account. Never use an error as a reason to silently submit a second fee.')+mock('offline','VERIFICATION','The API is temporarily unavailable','Keep the last known requests visible. Explain the stale state and pause new position actions. Refresh checks the same data; it does not clear it.')+'''</div>'''+table(['State','What the user sees','What must not happen'],[
('No wallet / wrong network','A clear Connect or switch-network action in context. The amount and chosen offer remain saved.','Discarding the draft, changing the user’s selected account silently, or hiding the intended chain.'),
('Wallet opened, app resumed','The same quote/payment/position action. A pending transaction offers recovery rather than another send.','Duplicate fee, duplicated approval/deposit, or “fresh test” behavior on app resume.'),
('Unpaid quote expired','Preserve the entered amount. Offer a fresh unpaid review using the existing fee-quote policy.','Pretend the old fee quote is valid indefinitely because the mobile layout hides a countdown.'),
('Payment accepted, creator offline','Saved C06 request with the correct readiness/progress message.','Treat signer inactivity as a missing payment or reintroduce C05.'),
('Premium partially funded','Show waiting-for-funding progress; LP entry remains unavailable.','Enabling deposit from a local animation or a guessed percentage.'),
('Position transferred / account changed','Refresh current bearer ownership and present only the actions available to the current wallet.','Grant withdrawal because the wallet originally requested the vault.'),
('Admin near/over target','Advisory banner only in authenticated admin Portfolio. Paid requests remain possible.','Expose private budget figures in Home or a modal; reintroduce a hard quota.'),
('Storage denied / another tab active','Use the existing recovery failure behavior and clear messaging. Maintain a single canonical interpretation of payment evidence.','Claim durable browser recovery succeeded when storage failed, or overwrite another payment record.')])+
'''<details class="finding" id="manual-refunds"><summary><h3><span class="tag">Product boundary</span>No removed workflow comes back</h3></summary><p>The mobile proposal does not add refund requests, requester retirement, C05, wallet/request quotas, gas-spending records or treasury balance checks. Manual refunds remain outside this frontend. Portfolio must support any number of separately paid requests, with pagination rather than a product cap.</p></details>''')

section('observed','07 / What the current mobile page tells us','''<p class="lead">The current page works responsively, but it still carries desktop-shaped priorities.</p><details class="finding" id="current-layout"><summary><h3><span class="tag">Observed</span>Navigation and introductory text occupy a large first-screen area</h3></summary><p>The current shell stacks its brand/navigation region and account controls above the content. The Home introduction remains two paragraphs. At narrow widths, each offer stacks APR, Duration and TVL vertically.</p><p><strong>Do:</strong> Consolidate the header, move frequent navigation to a bottom bar, shorten the default introduction and group Duration/TVL side by side.</p><p><strong>Why:</strong> Make the first useful offer and its comparison fields easier to reach without changing any offer economics.</p><p><strong>Gate:</strong> At a 390 × 844 layout, the proposed first card is visible without scrolling and all three cards require materially less vertical scrolling than the reference. Measure the implementation; do not treat this as an already achieved app result.</p></details><details class="finding" id="reference-screenshot"><summary><h3><span class="tag">Reference</span>Current 390 px app screenshot</h3></summary><p>This is the existing deployed layout captured by the previous compiled-browser check. It is evidence for the layout assessment, not a mobile mockup.</p><div class="evidence-scroll">__REFERENCE__</div></details><details class="finding" id="focus-sheets"><summary><h3><span class="tag">Observed</span>The modal already has valuable behavior to keep</h3></summary><p>The current modal has Back, a preserved deposit amount, LP details, clear fee copy and C06 recovery. The proposal changes the container and visual priority, not those contracts.</p><p><strong>Do:</strong> Add a mobile sheet layout in the existing modal layer, keeping one focus owner and the current state hooks.</p><p><strong>Gate:</strong> Escape, Back, close/reopen, wallet return and stale-response tests keep working. At 320 px, no action disappears under a keyboard or the bottom bar.</p></details>''')

section('delivery','08 / Implementation plan','''<p class="lead">Deliver in small, reviewable slices. Qualify the mobile shell before changing the request flow.</p><ol class="roadmap"><li><h3>Navigation and layout seams</h3><p>Add a compact mobile header and labelled bottom navigation to the shared shell. Reuse the existing routes. Put secondary destinations into More and keep role checks in their existing owner. Preserve the desktop rail.</p><div class="gate">Gate: direct links, Back/Forward, route focus, active labels and APR observation release still pass at phone/tablet/desktop widths.</div></li><li><h3>Home and Portfolio cards</h3><p>Use the compact offer composition below the chosen pane width. Keep Duration and TVL typography matched. Add status-first Portfolio grouping and a distinct saved-payment recovery card. Preserve pagination and last-known data.</p><div class="gate">Gate: three placeholder rows render; real/API mode does not inherit fake TVL. Long IDs, large values, empty state and admin-only advisory all fit.</div></li><li><h3>Mobile sheet container</h3><p>Adapt the shared modal to a bounded sheet with stable header, scrollable content and safe-area-aware action region. Integrate viewport/keyboard behavior. Keep amount → review → wallet → C06 state in the existing hooks.</p><div class="gate">Gate: native keyboard and wallet app switching work on iOS and Android; one payment remains one payment through interruption.</div></li><li><h3>Position lifecycle and Live APR</h3><p>Apply the same sheet system to LP approvals/deposit, claim and withdrawal. Give Live APR a touch pool picker and stacked comparisons without rewriting its data client or PNG feature.</p><div class="gate">Gate: exact fork-checked lifecycle still completes; ownership/maturity/funding guards hold. Pool changes preserve independent observation semantics.</div></li><li><h3>Qualification and rollout</h3><p>Run focused browser checks, then real-device checks. Publish a review build first; keep the current desktop and VNC environments intact. Back up static output and update the source ZIP/runbook before release.</p><div class="gate">Gate: the mobile acceptance matrix below is complete. Rollback restores static assets without clearing requests, browser recovery records or databases.</div></li></ol>'''+table(['Source seam','Expected change','Keep untouched'],[
('src/host/AppShell.tsx + Sidebar.tsx','Mobile header/navigation composition and one responsive shell owner.','Desktop palette, route owner and account/session ownership.'),
('src/incentives/IncentivesPage.tsx + MyVaults.tsx','Phone card layouts, comparison hierarchy, status/action grouping.','Offer economics, quota removals and API-derived role/position state.'),
('src/incentives/IncentiveModal.tsx + shared modal','Sheet layout, keyboard/safe-area behavior, focus restoration.','Exact payment terms, saved draft/payment records and explicit consent.'),
('DeploymentWaiting.tsx + VaultLifecyclePanel.tsx','Responsive status and transaction-action layout.','Canonical C06 verification, bearer rights and maturity guards.'),
('src/livePoolApr + src/merge','Touch toolbar and pane layout only where necessary.','Observation lifecycle, comparisons, math, history and PNG export.'),
('tests + operating docs','Regression cases and actual-device evidence.','Current VNC session; no mainnet deployment for design qualification.')])+
'''<p class="small">This plan does not assign invented hour estimates. The keyboard/wallet handoff is the main uncertainty and should be qualified early, not left to the final release check.</p>''')

section('acceptance','09 / Acceptance and device matrix','''<p class="lead">A narrow desktop browser is useful evidence. It is not a substitute for a real wallet on a phone.</p>'''+table(['Test surface','Coverage','Release requirement'],[
('Automated Chromium','320 × 568, 360 × 800, 390 × 844, 430 × 932; tablet 768 × 1024; desktop 1440 × 900.','No body overflow, 44 px targets, visible CTA, correct route state, matched TVL/Duration font, persistent draft and recovery.'),
('iOS Safari + mobile wallet','Safe areas, native decimal keyboard, rotation, larger text, wallet switch and return, browser Back.','Record actual device/browser versions and observed results. No duplicate transaction or discarded draft.'),
('Android Chrome + mobile wallet','Visual viewport resize, system navigation inset, provider handoff, screen lock/resume and network interruption.','Same recovery and action reachability gates as iOS.'),
('Keyboard + assistive technology','Tab/Shift-Tab, Escape, native disclosures, readable state labels and screen-reader route/dialog announcements.','Focus remains visible, trapped only while a modal is open, and restored to a sensible trigger on close.'),
('Backend fixture / fork','Lost payment callback, multi-request recovery, exact factory simulation, premium funding, LP entry, claim and mature withdrawal.','No weakening of canonical fee, funding, ownership or maturity checks. No live funds needed.'),
('Live APR fixture','Pool picker, three comparisons, route changes, stale/unavailable data and actual PNG pixels.','No accidental extra observers, stale baseline reuse or capture of surrounding navigation.')])+
'''<ul class="checks"><li>TVL is not shown as capacity or sourced from a private planning target.</li><li>Refresh status and Refresh vaults retain the existing request and never reset a test.</li><li>Buttons brighten by 15% with a mouse, remain legible on touch, and keep disabled appearance.</li><li>Opening the keyboard cannot hide Close, the focused input or the next required action.</li><li>Every user can make multiple independently paid requests; use pagination when needed.</li><li>Offline status retains evidence and disables only actions that depend on unavailable verification.</li><li>Mobile treatment does not alter the approved desktop table, sidebar or live APR data source.</li><li>Exported source, deployed files and documented build mode agree.</li></ul><div class="callout gold"><strong>Status of these gates:</strong> they are implementation acceptance criteria. The HTML document itself is checked for interaction, layout, offline assets and print behavior. It does not certify real-device wallet behavior or an implemented mobile redesign.</div>''')

PIN='f80eefffce1f02412f36e960e0e578e6a25af214'
paths=['src/host/AppShell.tsx','src/host/Sidebar.tsx','src/incentives/IncentivesPage.tsx','src/incentives/IncentiveModal.tsx','src/incentives/MyVaults.tsx','src/incentives/DeploymentWaiting.tsx','src/host/useDeploymentFlow.ts','src/livePoolApr/LivePoolAprPage.tsx']
for path in paths:
    assert (APP/path).is_file(),path
links=''.join('<li><a href="https://github.com/saffron-finance/saffron-scaffold/blob/'+PIN+'/feature-lab/live-apr-merge/'+path+'" target="_blank" rel="noreferrer">'+html.escape(path)+'</a></li>' for path in paths)
section('sources','10 / Scope, sources and handoff','''<div class="now-next"><div><h3>What is delivered</h3><p>A complete standalone HTML document with embedded fonts/assets, editable HTML/CSS/JavaScript mockup sources, an interactive prototype, the full flow gallery and an implementation/acceptance plan.</p></div><div><h3>What is not claimed</h3><p>The proposed mobile layout has not been merged into the app. Prototype payments are not real. OS keyboard behavior, mobile-wallet interoperability and production usability are not certified by these mockups.</p></div></div><p>Layout evidence is pinned to the existing source commit <code>'''+PIN+'''</code>. The separately requested 15% hover change is a small live-app update. The report’s gold APR/TVL/fee figures are illustrative unless explicitly identified as existing product copy.</p><ul class="sources">'''+links+'''</ul><div class="trace"><a href="https://clawbee.xyz/saffron/apps/feature-lab/live-apr-merge/" target="_blank" rel="noreferrer">Existing merge page ↗</a><a href="#interactive">Return to interactive prototype ↑</a><a href="#delivery">Implementation plan ↑</a></div><p class="report-footer-note">Font: Funnel Display, SIL Open Font License. App imagery is reused from the current project. No external scripts, fonts, trackers, API calls or wallet requests are required to read or interact with this HTML file. Print expands the document’s sections, then restores their prior state.</p>''')

reference=ROOT/'assets/current-home-390.png'
if reference.is_file():
    for item in sections:
        item['body_html']=item['body_html'].replace('__REFERENCE__','<img class="evidence-image" src="'+data(reference,'image/png')+'" alt="Current Saffron mobile Home layout at 390 CSS pixels: stacked navigation and tall offer cards">')
else:
    raise FileNotFoundError('Capture the current 390px reference before building this report')
model={'title':'Saffron, within reach.\nA complete mobile design plan.','eyebrow':'Mobile design study · 12 September 2026','description':'An immersive, interactive proposal for the existing Live APR merge frontend. Same Saffron character. A clearer mobile hierarchy. Complete request and recovery flows.','meta':'Current app: 15% modal hover · Proposed mobile layouts: not deployed · All mockup values are illustrative','sections':sections,'footer':'Saffron mobile design study · Full offline HTML · Prototype only · 12 September 2026'}
(ROOT/'report.json').write_text(json.dumps(model,ensure_ascii=False,indent=2)+'\n')
output=ROOT/'saffron-mobile-design-2026-09-12.html'
subprocess.run([sys.executable,str(RENDERER/'scripts/render.py'),'build',str(ROOT/'report.json'),str(output)],check=True,cwd=RENDERER)
page=output.read_text()
page=page.replace('</head>','<style id="saffron-mobile-study">'+FONT+'\n'+(ROOT/'report.css').read_text()+'</style></head>')
controls='''<script id="prototype-controls">
(() => {
 const frame=document.getElementById('mobile-prototype');
 const send=(command,value)=>frame.contentWindow.postMessage({type:'saffron-design',command,value},'*');
 document.getElementById('device-width').addEventListener('change',event=>document.getElementById('main-device').style.setProperty('--device-width',event.target.value+'px'));
 document.getElementById('prototype-state').addEventListener('change',event=>send('scenario',event.target.value));
 document.getElementById('prototype-scene').addEventListener('change',event=>{if(event.target.value)send('scene',event.target.value)});
 document.getElementById('keyboard-demo').addEventListener('change',event=>send('keyboard',event.target.checked));
 document.getElementById('reset-prototype').addEventListener('click',()=>{send('reset');document.getElementById('prototype-state').value='normal';document.getElementById('prototype-scene').value='';document.getElementById('keyboard-demo').checked=false;});
})();
</script>'''
page=page.replace('</body>',controls+'</body>')
license_text=(APP/'src/host/fonts/FunnelDisplay-OFL.txt').read_text().replace('--','—')
license_text='\n'.join(line.rstrip() for line in license_text.split('\n'))
page=page.replace('</head>','<!-- Embedded font license:\n'+license_text+'\n--></head>')
output.write_text(page)
print(json.dumps({'output':str(output),'bytes':output.stat().st_size,'sections':len(sections),'mockupFrames':page.count('<iframe')}))
